/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCampaignRouteImport } from './routes/app.campaign'
import { Route as AppMaternalRouteImport } from './routes/app.maternal'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTranslateRouteImport } from './routes/app.translate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCampaignRoute = AppCampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaternalRoute = AppMaternalRouteImport.update({
  id: '/maternal',
  path: '/maternal',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/campaign': typeof AppCampaignRoute
  '/app/maternal': typeof AppMaternalRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/campaign': typeof AppCampaignRoute
  '/app/maternal': typeof AppMaternalRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/campaign': typeof AppCampaignRoute
  '/app/maternal': typeof AppMaternalRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/translate': typeof AppTranslateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/campaign'
    | '/app/maternal'
    | '/app/settings'
    | '/app/translate'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/campaign'
    | '/app/maternal'
    | '/app/settings'
    | '/app/translate'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/campaign'
    | '/app/maternal'
    | '/app/settings'
    | '/app/translate'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/campaign': {
      id: '/app/campaign'
      path: '/campaign'
      fullPath: '/app/campaign'
      preLoaderRoute: typeof AppCampaignRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/maternal': {
      id: '/app/maternal'
      path: '/maternal'
      fullPath: '/app/maternal'
      preLoaderRoute: typeof AppMaternalRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/translate': {
      id: '/app/translate'
      path: '/translate'
      fullPath: '/app/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCampaignRoute: typeof AppCampaignRoute
  AppMaternalRoute: typeof AppMaternalRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTranslateRoute: typeof AppTranslateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCampaignRoute: AppCampaignRoute,
  AppMaternalRoute: AppMaternalRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTranslateRoute: AppTranslateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
